#!/bin/bash

# Copyright 2008 Vmetro.
# Phil Terry <pterry@vmetro.com>

# This program is free software; you can redistribute  it and/or modify it
# under  the terms of  the GNU General  Public License as published by the
# Free Software Foundation;  either version 2 of the  License, or (at your
# option) any later version.

if [ -f ~/.umemfddmarc ]; then
    . ~/.umemfddmarc
fi
function help () 
{

cat<<EOF
This script can install or uninstall this vfi system:
	$(pwd)
in your kernel:
	${kernelsrc:=/lib/modules/`uname -r`/build}

which should be a softlink:
$(ls -ld $kernelsrc)

Install (-i) copies the source files into the thee so that we can do
a kernel build.

Symlink (-s) just symlinks the include files into the kernel tree so
that the out of tree module build will work. This is a subset of 
Install.

Uninstall (-u) undoes either/both of the above.

Force (-f) forces install/uninstall to remove .orig backups.

Help (-h) Erm...

Verbose (-v) A longer version of Erm...
EOF
}

while getopts :viuscfh OPT; do
    case $OPT in
	v|+v)
	    V=-v
	    ;;
	i|+i)
	doInstall=Install
	dowhat=Install
	;;
	u|+u)
	doUninstall=Uninstall
	dowhat=Uninstall
	;;
	s|+s)
	doSymlink=Symlink
	dowhat=Symlink
	;;
	c|+c)
	doCopyleft=Copyleft
	dowhat=Copyleft
	;;
	f|+f)
	doforce=$OPT
	;;
	h|+h)
	help
	exit 0
	;;
	*)
	    echo "usage: ${0##*/} [+-v} [--] ARGS..."
	    exit 2
    esac
done
shift $[ OPTIND - 1 ]

if [ -z "$dowhat" ] ; then
    echo "What do you want to do?"
    select dowhat in "Install" "Uninstall" "Symlink" "Cancel" "Help"; do
	case x$dowhat in
	    x)
	    help
	    ;;
	    xInstall)
	    doInstall=Install
	    break
	    ;;
	    xUninstall)
	    doUninstall=Uninstall
	    break
	    ;;
	    xSymlink)
	    doSymlink=Symlink
	    break
	    ;;
	    xCancel)
	    echo -n "Timewaster! Then I guess we are all "
	    break
	    ;;
	    *)
	    help
	    ;;
	esac
    done
fi

if [ -n "$doInstall" -o -n "$doSymlink" ] ; then
    echo Populating ${kernelsrc:=/lib/modules/`uname -r`/build}/include/linux
    for file in *.h ; do
	if [ -L $kernelsrc/include/linux/$file ] ; then
	    if [ -n "$V" ]; then
		echo removing symlink for $file
		ls -l $kernelsrc/include/linux/$file
	    fi
	    rm $kernelsrc/include/linux/$file
	fi
	if [ -n "$doSymlink" ]; then
	    ln -s $(pwd)/$file $kernelsrc/include/linux/$file
	else
	    cp $V --backup=numbered $file $kernelsrc/include/linux
	fi
    done

    echo Populating $kernelsrc/drivers/vfi
    if [ -L $kernelsrc/drivers/vfi ] ; then
	rm $kernelsrc/drivers/vfi
    fi
    mkdir -p $kernelsrc/drivers/vfi
    for file in *.c Makefile Kbuild Kconfig ringbuf.h mpc10xdma.h ; do
	if [ -n "$doSymlink" ]; then
	    ln -s $(pwd)/$file $kernelsrc/drivers/vfi/$file
	else
	    cp $V --backup=numbered $file $kernelsrc/drivers/vfi
	fi

    done

    echo "Patching $kernelsrc/drivers/Kconfig"
patch -p0 <<EOF
--- $kernelsrc/drivers/Kconfig~	2007-08-02 13:26:43.000000000 -0700
+++ $kernelsrc/drivers/Kconfig	2007-08-14 10:13:47.000000000 -0700
@@ -82,6 +82,8 @@
 
 source "drivers/dma/Kconfig"
 
+source "drivers/vfi/Kconfig"
+
 source "drivers/auxdisplay/Kconfig"
 
 source "drivers/kvm/Kconfig"
EOF

    echo Populating $kernelsrc/Documentation/DocBook
    cp $V --backup=numbered DocBook/vfi.tmpl $kernelsrc/Documentation/DocBook
fi

if [ -n "$doUninstall" ] ; then
    if [ -L ${kernelsrc:=/lib/modules/`uname -r`/build}/drivers/vfi ]; then
	rm $kernelsrc/drivers/vfi
    elif [ -n "$doforce" ] ; then
	rm -rf $kernelsrc/drivers/vfi
    else
	rm $kernelsrc/drivers/vfi/*.[ch]
	rm $kernelsrc/drivers/vfi/{Kconfig,Kbuild,Makefile}
    fi
    rm $kernelsrc/include/linux/vfi*
    rm $kernelsrc/Documentation/DocBook/vfi.tmpl
patch -p0 -R <<EOF
--- $kernelsrc/drivers/Kconfig~	2007-08-02 13:26:43.000000000 -0700
+++ $kernelsrc/drivers/Kconfig	2007-08-14 10:13:47.000000000 -0700
@@ -82,6 +82,8 @@
 
 source "drivers/dma/Kconfig"
 
+source "drivers/vfi/Kconfig"
+
 source "drivers/auxdisplay/Kconfig"
 
 source "drivers/kvm/Kconfig"
EOF
fi 

if [ -n "$doCopyleft" ] ; then

for file in *.[ch] ; do
    grep -q Copyright $file
    if [ $? -ne 0 ] ; then
    sed -i -e "1i\
/* \\
 * \\
 * Copyright 2008 Vmetro. \\
 * ${name:-Phil Terry} <${email:-pterry}@vmetro.com> \\
 * \\
 * This program is free software; you can redistribute  it and/or modify it\\
 * under  the terms of  the GNU General  Public License as published by the\\
 * Free Software Foundation;  either version 2 of the  License, or  (at your\\
 * option) any later version.\\
 */\\
" $file
fi
done
fi

echo Done
